### ISSUE TITLE
Cannot change performance data root url

### ISSUE THREAD

**Issue by caidao22** [ginkgo-project/ginkgo-data-explorer#41]
The performance data root url seems to be locked to https://raw.githubusercontent.com/ginkgo-project/ginkgo-data/master/data. It does not load data from any other url.

**Comment by yhmtsai** [comment]
Hi, which url do you use?
If I want to use the 2020porting_solver branch of the ginkgo_data repo, 
I can change the data URL to https://raw.githubusercontent.com/ginkgo-project/ginkgo-data/intel_solver/data and click the icon next to URL.

**Comment by caidao22** [comment]
Thanks. I have figured out why it did not work for me.

1. It does not work with the Chrome browser on my Macbook. Switching to Safari works.
2. The raw URL (raw.githubusercontent.com) must be provided. I was using the URL of a GitHub repo directly.
